apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/refresh: hard
  name: app-components
  namespace: argocd
spec:
  project: arceye
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy: {}
  sources:
    - repoURL: https://github.com/jayl2kor/app-of-apps-test
      targetRevision: master
      path: app-of-apps
      helm:
        valueFiles:
          - $valueRepo/app-of-apps/values.yaml

    - ref: valueRepo
      targetRevision: master
      repoURL: https://github.com/jayl2kor/app-of-apps-test
