apiVersion: v1
data: 
  a:
    test: "true"
    test2:
      aa: 2
  aa:
    yeah: "true"
  aaa:
    yeah: "{{ .Values.configmap.data | toYaml | nindent 2 }}"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-22T09:36:17Z"
  name: workflow-parameter
  namespace: argocd