apiVersion: v1
data: 
  a:
    test: asf
    test2:
      aa: asff
  aa:
    yeah: fsaf
  aaa:
    yeah: asd
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-22T09:36:17Z"
  name: workflow-parameter
  namespace: argocd