apiVersion: v1
data: 
  a-1.0.1.yaml: |
    asersf: sdoify
    asfsaf: aasfsa 
  a-1.0.0.yaml: |
    asdassafas: sadsadasd 
    asfasfasfsa: safsafsaf

kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-22T09:36:17Z"
  name: workflow-parameter
  namespace: argocd