# apiVersion: v1
# data: {{ .Values.configmap.data | toYaml | nindent 2 }}
# kind: ConfigMap
# metadata:
#   creationTimestamp: "2023-09-22T09:36:17Z"
#   name: workflow-parameter
#   namespace: argocd
apiVersion: v1
data:
  Kind: ConfigMap

kind: ConfigMap
metadata:
  labels:
    argocd.argoproj.io/instance: helm-guestbook
  name: workflow-parameter
  namespace: argocd