apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/refresh: hard
  name: helm-guestbook
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  sources:
  - helm:
      valueFiles:
      - $valueRepo/values.yaml
      - $configmapRepo/configmap.yaml
    repoURL: {{ .Values.spec.sources.subapp1.repoURL }}
    targetRevision: {{ .Values.spec.sources.subapp1.targetRevision }}
    path: helm-guestbook
  - ref: valueRepo
    repoURL: {{ .Values.spec.sources.subapp1.repoURL }}
    targetRevision: {{ .Values.spec.sources.subapp1.targetRevision }}
  syncPolicy: {}